language: java
sudo: false
jdk:
- openjdk7
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- git submodule update --init
- cd sub/Growthcraft && git submodule update --init
- chmod +x ./gradlew
install: "./gradlew setupCIWorkspace -S"
script: |
  ./gradlew build &&
  ls -la build/libs
deploy:
  provider: releases
  api_key:
    secure: $RELEASE_SECURE_API_KEY
  file_glob: true
  file:
    build/libs/yatm-*-api.jar
    build/libs/yatm-*-dev.jar
    build/libs/yatm-*-javadoc.jar
    build/libs/yatm-*-release.jar
    build/libs/yatm-*-sources.jar
  skip_cleanup: true
  on:
    tags: true
